### ISSUE TITLE
where is steering_ref_dlc.mat?

### ISSUE THREAD

**Issue by lq0613** [srivats2794/Adaptive_Control_SteerByWire#1]
hello  you model maybe very usefull for my homework. And I would like to know where is the "steering_ref_dlc.mat"? Thank you!

**Comment by srivats2794** [comment]
Hey. Thank you for that catch. Forgot to upload it. Will do by end of day today.

**Comment by srivats2794** [comment]
However its just an input steering wheel angle profile. You can use your own too.

**Comment by lq0613** [comment]
&nbsp; &nbsp;Oh thanks for your reply! And thanks for updating. I can tell that the&nbsp;steering_ref_dlc.mat&nbsp;and&nbsp;EngineMap.xlsx &nbsp;and others are input profile. However, the format of these files may be different and I would like to run it as an example&nbsp;with your data.Forgive me that my English is not so good that I can express myself clearly.&nbsp;
&nbsp; &nbsp;Thank you for your replay and you really do me a big favor!
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Srivatsan ***@***.***&gt;; 
发送时间: 2022年6月29日(星期三) 上午8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [srivats2794/Adaptive_Control_SteerByWire] where is steering_ref_dlc.mat? (Issue #1)





 
However its just an input steering wheel angle profile. You can use your own too.

**Comment by srivats2794** [comment]
Done
